### ISSUE TITLE
Helm chart for orchestra is not deploying ingress.

### ISSUE THREAD

**Issue by sharmavijay86** [OpenUnison/openunison-k8s-login-oidc#42]
Hi may be this is with some updates but i am deploying helm chart. and it is not creating any ingress resource..

**Comment by mlbiam** [comment]
is a `Deployment` created?

**Comment by sharmavijay86** [comment]
Yes it is .. 
```
kubectl get deploy -n openunison                                                                                                                                                                            
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-oidc-proxy-orchestra   0/1     1            0           2m6s
openunison-operator         1/1     1            1           95m
openunison-orchestra        1/1     1            1           2m4s
```
kube-oidc-proxy-orchestra is in pending because it is not getting ingress.

**Comment by mlbiam** [comment]
What does your `values.yaml` look like?  chances are it doesn't like something there.  The operator pod's logs should have an error too when creating the `Ingress` object

**Comment by sharmavijay86** [comment]
Values.yaml 
```
network:
  openunison_host: "k8sou.eks.example.site"
  dashboard_host: "k8sdb.eks.example.site"
  api_server_host: "xxxxxxxxxxxxxx.eu-west-1.eks.amazonaws.com"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://xxxxxxxxxxxxxx.eu-west-1.eks.amazonaws.com
  createIngressCertificate: false
  ingress_type: nginx
  ingress_annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "docker.io/tremolosecurity/openunison-k8s-login-oidc:latest"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: my_eks_cluster
enable_impersonation: true


dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
certs:
  use_k8s_cm: false

trusted_certs: []
  #- name: idp
  #  pem_b64: SDFGSDFGHDFHSDFGSDGSDFGDS

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

oidc:
  client_id: xxxxxxxxxxxxxxxxxxxx
  auth_url: https://login.microsoftonline.com/xxxxxx/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/xxxxxxxxxxx/oauth2/v2.0/token
  user_in_idtoken: false
  userinfo_url: https://graph.microsoft.com/oidc/userinfo
  domain: ""
  scopes: openid email profile
  claims:
    sub: sub
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups
       

impersonation:
  use_jetstack: true
  jetstack_oidc_proxy_image: quay.io/jetstack/kube-oidc-proxy:v0.3.0
  explicit_certificate_trust: false
  ca_secret_name: ou-tls-secret
  
network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: false
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []
  pullSecret: ""

openunison:
  replicas: 1
  non_secret_data: {}
  secrets: []
```
I am using letsencrypt as ACME with cert-manager   
I am using ingress nginx deployment as 
```
kubectl apply https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.45.0/deploy/static/provider/aws/deploy.yaml
```
I am using dashboard as 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.5/aio/deploy/recommended.yaml
```

my secret file looks like 
```
apiVersion: v1
type: Opaque
metadata:
  name: orchestra-secrets-source
  namespace: openunison
data:
  OIDC_CLIENT_SECRET:  <base64-clinet-id-from-azure>
  K8S_DB_SECRET: aW0gYSBzZWNyZXQ=
  unisonKeystorePassword: aW0gYSBzZWNyZXQ=
kind: Secret
```
I am running on EKS.
