### ISSUE TITLE
Integration with traefik ingressroute

### ISSUE THREAD

**Issue by ddellarocca** [OpenUnison/openunison-k8s-login-oidc#44]
Hi,
I'm trying to deploy openunison in an eks cluster with traefik ingressroute and a certificate signed with cert-manager.
The ingressroute config is the following:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openunison
  namespace: openunison
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`ou.example.com`)
    services:
    - name: openunison-orchestra
      port: 443
  - kind: Rule
    match: Host(`ds.example.com`)
    services:
    - name: openunison-orchestra
      port: 443
  - kind: Rule
    match: Host(`api.example.com`)
    services:
    - name: openunison-orchestra
      port: 443
  tls:
    secretName: openunison-tls-certificate
``` 
With this configuration if i reach to https://ou.example.com/ i get `Internal Server Error`, if i change the port in each rule from `443` to `80` i can reach openunison dashboard correctly but i can't use kubectl because of this error `2021/05/28 15:39:27 http: panic serving 127.0.0.1:54726: oidc: issuer did not match the issuer returned by provider, expected "https://ou.example.com/auth/idp/k8s-login-cli" got "http://ou.example.com/auth/idp/k8s-login-cli"`.

I'm guessing that the problem is related to traefik refusing to expose an endpoint if the service certificate is invalid (self signed in this case) when using https to connect to the service.

I've also tested in a local cluster with kind and if i set `insecureskipverify` in traefik it works correctly but i can't set that flag on the production cluster.
Is there a way to workaround this issue?

PS. the secret `openunison-tls-certificate` is the certificate created by cert-manager and it is valid.
