### ISSUE TITLE
installing helm chart k8s-login-oidc results in error off of openunison_host

### ISSUE THREAD

**Issue by matty1979** [OpenUnison/openunison-k8s-login-oidc#47]
Installed and used values.yaml
```
network:
  openunison_host: "ou.ou-test.runshiftup.local"
  dashboard_host: "dashboard.ou-test.runshiftup.local"
  api_server_host: "api.ou-test.runshiftup.local"
  session_inactivity_timeout_seconds: 900
  k8s_url: http://127.0.0.1:49202/856a8c21-4dad-48d9-b82a-c9ba7dab23cc
  createIngressCertificate: true
  ingress_type: nginx
  ingress_annotations:
    kubernetes.io/ingress.class: nginx
  force_redirect_to_tls: true
  ingress_certificate: ou-tls-certificate
```
Going to `https://ou.ou-test.runshiftup.local:8443` redirects to `https://ou.ou-test.runshiftup.local:8443/login/ldap` 

It should be redirecting to my keycloak installation for login. I don't know where it's getting this login/ldap from.
